name: Deploy Backend

on:
  push:
    branches:
      - master
      - staging

  workflow_dispatch:

jobs:
  deploy-production:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy backend to production
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_PORT }}
          command_timeout: 10m
          script: |
            set -e

            cd /home/ubuntu/armenia-tourism/armenia-tourism-be

            git fetch origin
            git reset --hard origin/master

            docker compose build app queue scheduler

            docker compose up -d \
              --force-recreate \
              app queue scheduler nginx

            docker compose exec -T app php artisan migrate --force

            docker compose exec -T app php artisan optimize:clear
            docker compose exec -T app php artisan config:cache
            docker compose exec -T app php artisan route:cache

            docker compose restart queue scheduler

            docker image prune -f

  deploy-staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Deploy backend to staging
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          port: ${{ secrets.STAGING_PORT }}
          command_timeout: 10m
          script: |
            set -e

            cd /home/ubuntu/armenia-tourism/armenia-tourism-be

            git fetch origin
            git reset --hard origin/staging

            docker compose build app queue scheduler

            docker compose up -d \
              --force-recreate \
              app queue scheduler nginx

            docker compose exec -T app php artisan migrate --force

            docker compose exec -T app php artisan optimize:clear
            docker compose exec -T app php artisan config:cache
            docker compose exec -T app php artisan route:cache

            docker compose restart queue scheduler

            docker image prune -f
